#!/usr/bin/env bash
#
# Regenerates tests/lib/images.nix from the images referenced by every compose
# file in the repo.
#
# The VM suites run with no network (that is what makes them reproducible), so
# every image has to be in the Nix store before the test starts. This script
# resolves each `image:` reference to a content-addressed {digest, hash} pin
# that dockerTools.pullImage can fetch, and the suites `docker load` them into
# the guest.
#
# Run this after changing any image tag in a compose file. The drift lint in
# tests/lib/lints.nix fails the suite if you forget, so a stale pin surfaces as
# a test failure rather than as a suite that quietly tests the old image.
#
# Usage:
#   ./tests/update-images.sh            # all images
#   ./tests/update-images.sh light      # skip the multi-GB ones
#
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="tests/lib/images.nix"
TIER="${1:-all}"

# Images too large to pin on every developer machine by default. They are only
# needed by suites/stacks-heavy.nix.
HEAVY_RE='paperless-ngx|goauthentik|apache/tika|gotenberg|backrest'

# Images referenced in compose but not resolvable from a public registry.
# Format: <compose reference>|<substitute reference>|<reason>
# (Empty since 2026-08-30: the caddy-cloudflare fork is published on ghcr —
# public, anonymous pulls — so the suites now load the REAL image, DNS-01
# plugin included, closing README finding #3's substitution.)
declare -a SUBSTITUTES=()

echo "==> Collecting image references from compose files"
# .claude/worktrees/ holds Claude Code checkouts of this same repo. Their
# compose files are stale copies, and scanning them pins images no live stack
# references — including tags that were deleted from the tree months ago.
mapfile -t REFS < <(
  find . -name compose.yaml -not -path './.claude/*' -print0 \
    | xargs -0 grep -hoE '^\s*image:\s*\S+' \
    | sed -E 's/^\s*image:\s*//' \
    | sort -u
)

# Apply substitutions and record them for the generated header.
declare -a PINS=()
declare -a NOTES=()
for ref in "${REFS[@]}"; do
  sub=""
  for s in "${SUBSTITUTES[@]}"; do
    IFS='|' read -r from to why <<<"$s"
    if [[ "$ref" == "$from" ]]; then
      sub="$to"
      NOTES+=("$from -> $to ($why)")
    fi
  done
  PINS+=("${sub:-$ref}|$ref")
done

echo "==> Pinning ${#PINS[@]} images (tier: $TIER)"
declare -a UNRESOLVED=()
declare -a SKIPPED=()
{
  echo "# GENERATED by tests/update-images.sh — do not edit by hand."
  echo "#"
  echo "# Maps a compose \`image:\` reference to a content-addressed pin that"
  echo "# dockerTools.pullImage can fetch offline. \`composeRef\` is the string as it"
  echo "# appears in the compose file; the suites key off it so the drift lint can"
  echo "# compare the two."
  if [[ ${#NOTES[@]} -gt 0 ]]; then
    echo "#"
    echo "# Substitutions in effect:"
    for n in "${NOTES[@]}"; do
      echo "#   $n" | fold -s -w 76 | sed '2,$s/^/#     /'
    done
  fi
  echo "{"
} >"$OUT.tmp"

for pin in "${PINS[@]}"; do
  IFS='|' read -r fetchRef composeRef <<<"$pin"

  if [[ "$TIER" == "light" && "$fetchRef" =~ $HEAVY_RE ]]; then
    echo "    skip (heavy): $fetchRef"
    SKIPPED+=("$composeRef")
    continue
  fi

  name="${fetchRef%:*}"
  tag="${fetchRef##*:}"

  # The image is retagged on load to whatever the compose file asks for, so a
  # substituted image still satisfies `image:` inside the guest.
  finalName="${composeRef%:*}"
  finalTag="${composeRef##*:}"
  if [[ "$fetchRef" != "$composeRef" ]]; then
    echo "    $fetchRef (loaded as $composeRef)"
  else
    echo "    $fetchRef"
  fi

  # A tag that does not resolve is a real deploy-blocking bug in the compose
  # file, not a reason to abort the run. Record it and keep going, so one bad
  # reference does not hide the state of every other image.
  # --final-image-{name,tag} must be passed here, not only recorded in the pin:
  # they are written into the tarball's manifest, so the output hash depends on
  # them. Computing the hash without them and retagging in Nix yields a
  # fixed-output hash mismatch at build time.
  #
  # THREE attempts with backoff before declaring non-existence: registries
  # hiccup. Two consecutive full runs each produced ONE phantom "missing"
  # image (prowlarr, then immich-ml) that skopeo confirmed present moments
  # later — a single failed fetch is evidence of nothing.
  meta="" resolved=0
  for attempt in 1 2 3; do
    if meta=$(nix run nixpkgs#nix-prefetch-docker -- \
      --image-name "$name" --image-tag "$tag" \
      --final-image-name "$finalName" --final-image-tag "$finalTag" \
      --quiet 2>/dev/null); then
      resolved=1
      break
    fi
    [[ $attempt -lt 3 ]] && { echo "      fetch failed (attempt $attempt/3), retrying..."; sleep $((attempt * 5)); }
  done
  if [[ $resolved -eq 0 ]]; then
    echo "      UNRESOLVED — no such tag in the registry (3 attempts)"
    UNRESOLVED+=("$composeRef")
    continue
  fi

  digest=$(sed -nE 's/.*imageDigest = "([^"]+)".*/\1/p' <<<"$meta")
  hash=$(sed -nE 's/.*hash = "([^"]+)".*/\1/p' <<<"$meta")

  attr=$(tr '/:.' '___' <<<"$composeRef")
  cat >>"$OUT.tmp" <<NIXEOF
  "$attr" = {
    composeRef = "$composeRef";
    imageName = "$name";
    imageDigest = "$digest";
    hash = "$hash";
    finalImageName = "$finalName";
    finalImageTag = "$finalTag";
  };
NIXEOF
done

# Emit the bookkeeping lists so lints can act on them. `_unresolved` is what
# makes a bad tag fail a test run instead of only scrolling past in this
# script's output; `_skipped` keeps a light-tier run from being mistaken for
# full coverage.
{
  echo "  _unresolved = ["
  for u in ${UNRESOLVED+"${UNRESOLVED[@]}"}; do echo "    \"$u\""; done
  echo "  ];"
  echo "  _skipped = ["
  for s in ${SKIPPED+"${SKIPPED[@]}"}; do echo "    \"$s\""; done
  echo "  ];"
  echo "}"
} >>"$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "==> Wrote $OUT"

if [[ ${#UNRESOLVED[@]} -gt 0 ]]; then
  echo
  echo "!! ${#UNRESOLVED[@]} image reference(s) do not exist in their registry."
  echo "   These cannot be pulled on the real host either — they are deploy-blocking:"
  for u in "${UNRESOLVED[@]}"; do echo "     $u"; done
  exit 1
fi
