#!/usr/bin/env bash
#
# Regenerates tests/lib/images.nix from the images referenced by every compose
# file in the repo.
#
# The VM suites run with no network (that is what makes them reproducible), so
# every image has to be in the Nix store before the test starts. This script
# resolves each `image:` reference to a content-addressed {digest, hash} pin
# that dockerTools.pullImage can fetch, and the suites `docker load` them into
# the guest.
#
# Run this after changing any image tag in a compose file. The drift lint in
# tests/lib/lints.nix fails the suite if you forget, so a stale pin surfaces as
# a test failure rather than as a suite that quietly tests the old image.
#
# Usage:
#   ./tests/update-images.sh            # all images
#   ./tests/update-images.sh light      # skip the multi-GB ones
#
set -euo pipefail

# Resolved BEFORE the cd: the lock guard below re-execs this script, and a
# relative $0 (cd tests; ./update-images.sh) no longer resolves once the
# working directory is the repo root.
SELF=$(readlink -f "$0")

cd "$(dirname "$0")/.."
OUT="tests/lib/images.nix"
TIER="${1:-all}"

# ---------------------------------------------------------------------------
# Single-instance guard
# ---------------------------------------------------------------------------
# This script truncates "$OUT.tmp" once and then APPENDS one entry per image
# before `mv`ing it into place, so two overlapping runs interleave their
# entries and one of them moves a corrupt file over images.nix. That failure
# does not look like a race: entries simply go missing, which reads exactly
# like the registry having lost a tag.
#
# It is easy to hit, because a full run takes long enough to want to
# background — and "wait for the tmpfile to disappear" is NOT a safe way to
# tell whether a run is in progress: the tmpfile does not exist during the
# opening collect-references phase, so that guard fires early and starts a
# second run on top of the first. Waiting on the PROCESS is the only correct
# way; this lock makes getting it wrong harmless.
#
# -E 99 so a lock failure is distinguishable from the exit 1 this script uses
# for unresolved tags.
LOCKFILE="${TMPDIR:-/tmp}/basicbastard-update-images.lock"
if [ "${UPDATE_IMAGES_LOCKED:-}" != "1" ]; then
  rc=0
  UPDATE_IMAGES_LOCKED=1 flock -E 99 -w 0 "$LOCKFILE" "$SELF" "$@" || rc=$?
  if [ "$rc" -eq 99 ]; then
    echo "!! another update-images.sh already holds $LOCKFILE — refusing to" >&2
    echo "   run concurrently (they would interleave into one images.nix.tmp)." >&2
  fi
  exit "$rc"
fi

# Images too large to pin on every developer machine by default. They are only
# needed by suites/stacks-heavy.nix.
HEAVY_RE='paperless-ngx|goauthentik|apache/tika|gotenberg|backrest'

# Images referenced in compose but not resolvable from a public registry.
# Format: <compose reference>|<substitute reference>|<reason>
declare -a SUBSTITUTES=(
  "ghcr.io/idanreed/caddy-cloudflare:2.11.2|caddy:2.11.2|fork image is built by .github/workflows/build-caddy.yml and is not published yet; the DNS-01 plugin it adds is unused in the suites, which force 'tls internal'"
)

echo "==> Collecting image references from compose files"
# .claude/worktrees/ holds Claude Code checkouts of this same repo. Their
# compose files are stale copies, and scanning them pins images no live stack
# references — including tags that were deleted from the tree months ago.
mapfile -t REFS < <(
  find . -name compose.yaml -not -path './.claude/*' -print0 \
    | xargs -0 grep -hoE '^\s*image:\s*\S+' \
    | sed -E 's/^\s*image:\s*//' \
    | sort -u
)

# Apply substitutions and record them for the generated header.
declare -a PINS=()
declare -a NOTES=()
for ref in "${REFS[@]}"; do
  sub=""
  for s in "${SUBSTITUTES[@]}"; do
    IFS='|' read -r from to why <<<"$s"
    if [[ "$ref" == "$from" ]]; then
      sub="$to"
      NOTES+=("$from -> $to ($why)")
    fi
  done
  PINS+=("${sub:-$ref}|$ref")
done

echo "==> Pinning ${#PINS[@]} images (tier: $TIER)"
declare -a UNRESOLVED=()
declare -a SKIPPED=()
{
  echo "# GENERATED by tests/update-images.sh — do not edit by hand."
  echo "#"
  echo "# Maps a compose \`image:\` reference to a content-addressed pin that"
  echo "# dockerTools.pullImage can fetch offline. \`composeRef\` is the string as it"
  echo "# appears in the compose file; the suites key off it so the drift lint can"
  echo "# compare the two."
  if [[ ${#NOTES[@]} -gt 0 ]]; then
    echo "#"
    echo "# Substitutions in effect:"
    for n in "${NOTES[@]}"; do
      echo "#   $n" | fold -s -w 76 | sed '2,$s/^/#     /'
    done
  fi
  echo "{"
} >"$OUT.tmp"

for pin in "${PINS[@]}"; do
  IFS='|' read -r fetchRef composeRef <<<"$pin"

  if [[ "$TIER" == "light" && "$fetchRef" =~ $HEAVY_RE ]]; then
    echo "    skip (heavy): $fetchRef"
    SKIPPED+=("$composeRef")
    continue
  fi

  name="${fetchRef%:*}"
  tag="${fetchRef##*:}"

  # The image is retagged on load to whatever the compose file asks for, so a
  # substituted image still satisfies `image:` inside the guest.
  finalName="${composeRef%:*}"
  finalTag="${composeRef##*:}"
  if [[ "$fetchRef" != "$composeRef" ]]; then
    echo "    $fetchRef (loaded as $composeRef)"
  else
    echo "    $fetchRef"
  fi

  # A tag that does not resolve is a real deploy-blocking bug in the compose
  # file, not a reason to abort the run. Record it and keep going, so one bad
  # reference does not hide the state of every other image.
  # --final-image-{name,tag} must be passed here, not only recorded in the pin:
  # they are written into the tarball's manifest, so the output hash depends on
  # them. Computing the hash without them and retagging in Nix yields a
  # fixed-output hash mismatch at build time.
  #
  # RETRIED, and the stderr is KEPT. This used to be a single attempt with
  # `2>/dev/null` and the message "no such tag in the registry" — which is a
  # claim the script had not actually checked. nix-prefetch-docker exits
  # non-zero for a manifest 404, a registry 5xx, a rate limit, a TLS reset and
  # a mid-pull disconnect alike, and the big multi-hundred-megabyte images
  # (immich-machine-learning is the repeat offender) hit the transient ones
  # often enough that a full run kept coming back with a "deploy-blocking"
  # finding for a tag that resolved fine on the next attempt. Blaming the
  # compose file for a network blip is worse than useless: it sends you
  # looking for a tag-shape bug that does not exist.
  #
  # Independently confirmed by the operator on main, whose own fix noted TWO
  # consecutive full runs each producing exactly ONE phantom "missing" image
  # (prowlarr, then immich-ml) that skopeo found present moments later. That
  # version kept `2>/dev/null` and the "no such tag in the registry" wording,
  # so it still asserted a cause it had discarded the evidence for; this one
  # keeps the stderr and says only what it can support. Backoff is 10s/20s
  # rather than 5s/10s for the same reason — the failures are transient and
  # worth waiting out.
  errfile=$(mktemp)
  meta=""
  for attempt in 1 2 3; do
    if meta=$(nix run nixpkgs#nix-prefetch-docker -- \
      --image-name "$name" --image-tag "$tag" \
      --final-image-name "$finalName" --final-image-tag "$finalTag" \
      --quiet 2>"$errfile"); then
      break
    fi
    meta=""
    [[ $attempt -lt 3 ]] && { echo "      attempt $attempt failed, retrying"; sleep $((attempt * 10)); }
  done

  if [[ -z "$meta" ]]; then
    echo "      UNRESOLVED after 3 attempts. Last error:"
    sed 's/^/        /' <(tail -n 5 "$errfile")
    echo "        (verify by hand before editing the compose file — this is"
    echo "         only a bad tag if the error says the manifest is unknown)"
    UNRESOLVED+=("$composeRef")
    rm -f "$errfile"
    continue
  fi
  rm -f "$errfile"

  digest=$(sed -nE 's/.*imageDigest = "([^"]+)".*/\1/p' <<<"$meta")
  hash=$(sed -nE 's/.*hash = "([^"]+)".*/\1/p' <<<"$meta")

  attr=$(tr '/:.' '___' <<<"$composeRef")
  cat >>"$OUT.tmp" <<NIXEOF
  "$attr" = {
    composeRef = "$composeRef";
    imageName = "$name";
    imageDigest = "$digest";
    hash = "$hash";
    finalImageName = "$finalName";
    finalImageTag = "$finalTag";
  };
NIXEOF
done

# Emit the bookkeeping lists so lints can act on them. `_unresolved` is what
# makes a bad tag fail a test run instead of only scrolling past in this
# script's output; `_skipped` keeps a light-tier run from being mistaken for
# full coverage.
{
  echo "  _unresolved = ["
  for u in ${UNRESOLVED+"${UNRESOLVED[@]}"}; do echo "    \"$u\""; done
  echo "  ];"
  echo "  _skipped = ["
  for s in ${SKIPPED+"${SKIPPED[@]}"}; do echo "    \"$s\""; done
  echo "  ];"
  echo "}"
} >>"$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "==> Wrote $OUT"

if [[ ${#UNRESOLVED[@]} -gt 0 ]]; then
  echo
  echo "!! ${#UNRESOLVED[@]} image reference(s) do not exist in their registry."
  echo "   These cannot be pulled on the real host either — they are deploy-blocking:"
  for u in "${UNRESOLVED[@]}"; do echo "     $u"; done
  exit 1
fi
