# GENERATED by tests/update-images.sh — do not edit by hand.
#
# Maps a compose `image:` reference to a content-addressed pin that
# dockerTools.pullImage can fetch offline. `composeRef` is the string as it
# appears in the compose file; the suites key off it so the drift lint can
# compare the two.
{
  "alpine_3_21" = {
    composeRef = "alpine:3.21";
    imageName = "alpine";
    imageDigest = "sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d";
    hash = "sha256-LF7w479+22OQjiScUf+wSKIK12isourh11CrfiztdzI=";
    finalImageName = "alpine";
    finalImageTag = "3.21";
  };
  "alpine_git_v2_54_0" = {
    composeRef = "alpine/git:v2.54.0";
    imageName = "alpine/git";
    imageDigest = "sha256:4f9488b7295baec153a9953479690f835ad4699b1d9f11e3897a4485c224fc3e";
    hash = "sha256-zVQnHeGiBUpRiC2YiKDcbq7ilFv+d5utNfynIpX/qAk=";
    finalImageName = "alpine/git";
    finalImageTag = "v2.54.0";
  };
  "apache_tika_3_3_0_0" = {
    composeRef = "apache/tika:3.3.0.0";
    imageName = "apache/tika";
    imageDigest = "sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583";
    hash = "sha256-fWuqnkv542d0oMcRqpEtis8sFbmqO6VQ9RtU4dsg+g4=";
    finalImageName = "apache/tika";
    finalImageTag = "3.3.0.0";
  };
  "binwiederhier_ntfy_v2_11_0" = {
    composeRef = "binwiederhier/ntfy:v2.11.0";
    imageName = "binwiederhier/ntfy";
    imageDigest = "sha256:4a7d0f0adc6d5d9fc36e64ab55ef676e76e124a2bdd50ce115b6d9c1c7430294";
    hash = "sha256-YyFHylsrqo9yYDFOgnbn9dJhkB1Ol6Te4mX0N1fRD2s=";
    finalImageName = "binwiederhier/ntfy";
    finalImageTag = "v2.11.0";
  };
  "clamav_clamav_1_5" = {
    composeRef = "clamav/clamav:1.5";
    imageName = "clamav/clamav";
    imageDigest = "sha256:f0954d679017eb6d48221e2b2be3ac5457bf278a844f39b672376f55a085f591";
    hash = "sha256-cWHxno7evBi8pCnFvXlRAwMbJrYdcjd9xa6tzcheA9k=";
    finalImageName = "clamav/clamav";
    finalImageTag = "1.5";
  };
  "codeberg_org_forgejo_forgejo_16_0" = {
    composeRef = "codeberg.org/forgejo/forgejo:16.0";
    imageName = "codeberg.org/forgejo/forgejo";
    imageDigest = "sha256:7c4e1db440be7b2ca685b49d0d7864cdd78e92431f531bf7893659def8200fc5";
    hash = "sha256-hXuu9eeWYGfUba1aFChZcrtyw8Kpz3drDKnXv3Okp8Q=";
    finalImageName = "codeberg.org/forgejo/forgejo";
    finalImageTag = "16.0";
  };
  "corentinth_it-tools_2024_10_22-7ca5933" = {
    composeRef = "corentinth/it-tools:2024.10.22-7ca5933";
    imageName = "corentinth/it-tools";
    imageDigest = "sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f";
    hash = "sha256-+XnDXJcbgU9VoakkAGEui2Sv/vnejRVdg/qaFWHDejk=";
    finalImageName = "corentinth/it-tools";
    finalImageTag = "2024.10.22-7ca5933";
  };
  "crazymax_samba_4_23_8" = {
    composeRef = "crazymax/samba:4.23.8";
    imageName = "crazymax/samba";
    imageDigest = "sha256:b37f7af97c773eddb593537f64da6389e5ee6695bcecf44f3ba1a8a6bcf34125";
    hash = "sha256-XK+bajrD5jIoedhyz0Ldz5NZoHm15b1aGKK+zRZnP1k=";
    finalImageName = "crazymax/samba";
    finalImageTag = "4.23.8";
  };
  "ddvk_rmfakecloud_0_0_31" = {
    composeRef = "ddvk/rmfakecloud:0.0.31";
    imageName = "ddvk/rmfakecloud";
    imageDigest = "sha256:2f5c45cbf0c53a5fb7bc38c97dd9d26d3701c5a5e04d0e9206311ba258c32fac";
    hash = "sha256-FKF23Abhdcc1k9WAKR37G4S5gWsEogDQ40g4/cq+1oM=";
    finalImageName = "ddvk/rmfakecloud";
    finalImageTag = "0.0.31";
  };
  "eclipse-mosquitto_2_0_22" = {
    composeRef = "eclipse-mosquitto:2.0.22";
    imageName = "eclipse-mosquitto";
    imageDigest = "sha256:212f89e1eaeb2c322d6441b64396e3346026674db8fa9c27beac293405c32b3c";
    hash = "sha256-4Us5YbEUax2PoMoSM37TKTRjmqJqHO24yUKYiPK3+is=";
    finalImageName = "eclipse-mosquitto";
    finalImageTag = "2.0.22";
  };
  "fireflyiii_core_version-6_6_6" = {
    composeRef = "fireflyiii/core:version-6.6.6";
    imageName = "fireflyiii/core";
    imageDigest = "sha256:ae69fdd95cdef9038cd7a460a5aec731f14813973e4f096511d5a4ea9ff0e972";
    hash = "sha256-iFqkIHBU4R7F66Nty9WFyRug+oMD/2ACLamHds8njtY=";
    finalImageName = "fireflyiii/core";
    finalImageTag = "version-6.6.6";
  };
  "fireflyiii_data-importer_version-2_3_4" = {
    composeRef = "fireflyiii/data-importer:version-2.3.4";
    imageName = "fireflyiii/data-importer";
    imageDigest = "sha256:26459e1f014544f1ae56d1beed9c6a0ddf208b1eaa24cf11fa77ebd1f51422c8";
    hash = "sha256-7a0Ge9he4PGAeDsF3h1wlqqo97r7Y25jQlPrK6yc0Ls=";
    finalImageName = "fireflyiii/data-importer";
    finalImageTag = "version-2.3.4";
  };
  "freikin_dawarich_1_14_0" = {
    composeRef = "freikin/dawarich:1.14.0";
    imageName = "freikin/dawarich";
    imageDigest = "sha256:f251f08d6330a9b22506c862407e53b0b4aec620a63953a446e19cd610d7d476";
    hash = "sha256-VsWtODv4u5QE/TbUkffYgvdNy6gHR1SK4h6Ece84K0k=";
    finalImageName = "freikin/dawarich";
    finalImageTag = "1.14.0";
  };
  "garethgeorge_backrest_v1_9_1" = {
    composeRef = "garethgeorge/backrest:v1.9.1";
    imageName = "garethgeorge/backrest";
    imageDigest = "sha256:96feace1c73a6869ca581348c1ecc35dfeab39be9b0e6c9aaabe4bc7889435be";
    hash = "sha256-lxt64sZTGpYrxVZFPp4jlbl8ai/bd9C6i2h835jyO74=";
    finalImageName = "garethgeorge/backrest";
    finalImageTag = "v1.9.1";
  };
  "getmeili_meilisearch_v1_41_0" = {
    composeRef = "getmeili/meilisearch:v1.41.0";
    imageName = "getmeili/meilisearch";
    imageDigest = "sha256:860fa4baed04ae1c235de870edab0c8006227546dea1bbb6411fbfc5e27cf1db";
    hash = "sha256-8l73wnHweuexM9dc7yZCV4+T96vx70PCcRx7Q8FrjmE=";
    finalImageName = "getmeili/meilisearch";
    finalImageTag = "v1.41.0";
  };
  "ghcr_io_advplyr_audiobookshelf_2_36_0" = {
    composeRef = "ghcr.io/advplyr/audiobookshelf:2.36.0";
    imageName = "ghcr.io/advplyr/audiobookshelf";
    imageDigest = "sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e";
    hash = "sha256-az9pta5k2CZ68VLGCI/svdzMhEjNMofOXe4QBFsWwFg=";
    finalImageName = "ghcr.io/advplyr/audiobookshelf";
    finalImageTag = "2.36.0";
  };
  "ghcr_io_alam00000_bentopdf_1_16_1" = {
    composeRef = "ghcr.io/alam00000/bentopdf:1.16.1";
    imageName = "ghcr.io/alam00000/bentopdf";
    imageDigest = "sha256:d98223eb82661a9f6624a813ed7fc44ad4f80e761e24116a721e1cd891ac8c3f";
    hash = "sha256-XC2oqDa8p50Ck1u92JqHX/Pm//94OOJmiTEdOWHEAU4=";
    finalImageName = "ghcr.io/alam00000/bentopdf";
    finalImageTag = "1.16.1";
  };
  "ghcr_io_blakeblackshear_frigate_0_17_2" = {
    composeRef = "ghcr.io/blakeblackshear/frigate:0.17.2";
    imageName = "ghcr.io/blakeblackshear/frigate";
    imageDigest = "sha256:d4351369984d4a9e2a49ac59736f6490856a7ea11f7790040746d21496967010";
    hash = "sha256-VnjWSg6Ym0hBCQn9o9ujaDyXJrMN1Y6AaFj/xVUsvw4=";
    finalImageName = "ghcr.io/blakeblackshear/frigate";
    finalImageTag = "0.17.2";
  };
  "ghcr_io_calibrain_shelfmark_1_3_13" = {
    composeRef = "ghcr.io/calibrain/shelfmark:1.3.13";
    imageName = "ghcr.io/calibrain/shelfmark";
    imageDigest = "sha256:ee0f3a15a8cc37a43a39fb9e768eac0c9a4ac328014b9b914bad7c1be232bd90";
    hash = "sha256-JQYBXwf9vdUolIkebA1qjjADZ0vdUjzjE9kfV6TVmdg=";
    finalImageName = "ghcr.io/calibrain/shelfmark";
    finalImageTag = "1.3.13";
  };
  "ghcr_io_civilblur_mazanoke_v1_1_5" = {
    composeRef = "ghcr.io/civilblur/mazanoke:v1.1.5";
    imageName = "ghcr.io/civilblur/mazanoke";
    imageDigest = "sha256:e43dc48de575b7a032bbefd96b890d69c1f141417e43d5d096469aa1398711d6";
    hash = "sha256-4Jcx9/SR4/FGifTh1SBWzD2JKueaysmv4ndDQdcwmE0=";
    finalImageName = "ghcr.io/civilblur/mazanoke";
    finalImageTag = "v1.1.5";
  };
  "ghcr_io_cleanuparr_cleanuparr_2_10_5" = {
    composeRef = "ghcr.io/cleanuparr/cleanuparr:2.10.5";
    imageName = "ghcr.io/cleanuparr/cleanuparr";
    imageDigest = "sha256:c7cd53ad559a67147637de3d825f66ef6e6a5498490b73f49c6e4d72f13bed76";
    hash = "sha256-nDwB4DkBKrnJM2IVTDZSzTroCBqkkmfSyEtVRek4dpE=";
    finalImageName = "ghcr.io/cleanuparr/cleanuparr";
    finalImageTag = "2.10.5";
  };
  "ghcr_io_dictionarry-hub_profilarr_2_2_0" = {
    composeRef = "ghcr.io/dictionarry-hub/profilarr:2.2.0";
    imageName = "ghcr.io/dictionarry-hub/profilarr";
    imageDigest = "sha256:ddcdd0f340043c2ec0a85ca74b9a6be9be42b1c0288c75fc36a26a43f695860b";
    hash = "sha256-mWa8eAFbR/oqmJGYBs1QjbNoRLWHJud4Gfr651Fkur0=";
    finalImageName = "ghcr.io/dictionarry-hub/profilarr";
    finalImageTag = "2.2.0";
  };
  "ghcr_io_getarcaneapp_arcane_v1_17_4" = {
    composeRef = "ghcr.io/getarcaneapp/arcane:v1.17.4";
    imageName = "ghcr.io/getarcaneapp/arcane";
    imageDigest = "sha256:97492274e59c9f822a9c49d67981912b81919c0edad6094e496fa3507348082e";
    hash = "sha256-mqBArBFkyP5M6KOsb2RX974vPpDh9W/RtxoIpmt7IcQ=";
    finalImageName = "ghcr.io/getarcaneapp/arcane";
    finalImageTag = "v1.17.4";
  };
  "ghcr_io_goauthentik_server_2026_5_6" = {
    composeRef = "ghcr.io/goauthentik/server:2026.5.6";
    imageName = "ghcr.io/goauthentik/server";
    imageDigest = "sha256:ed120caf710ccf82ef0026f0bc74e51615bc95ebff228a7a2d6fc60c441c3868";
    hash = "sha256-58hlqmnlLLaIz5S1EBHayHUOSoiQmULhe76jnAiNl/k=";
    finalImageName = "ghcr.io/goauthentik/server";
    finalImageTag = "2026.5.6";
  };
  "ghcr_io_home-assistant_home-assistant_2026_8_3" = {
    composeRef = "ghcr.io/home-assistant/home-assistant:2026.8.3";
    imageName = "ghcr.io/home-assistant/home-assistant";
    imageDigest = "sha256:14931c6b13756317849f46da1d01b45937a1150db66c081cfe529d48215943fe";
    hash = "sha256-/+233TaTLpk1T7vu8Nkug4xkaMa81bwnu5j93ORfZgg=";
    finalImageName = "ghcr.io/home-assistant/home-assistant";
    finalImageTag = "2026.8.3";
  };
  "ghcr_io_idanreed_caddy-cloudflare_2_11_2" = {
    composeRef = "ghcr.io/idanreed/caddy-cloudflare:2.11.2";
    imageName = "ghcr.io/idanreed/caddy-cloudflare";
    imageDigest = "sha256:a96289a08e6a1ba5dccc650a00b86083c0629329e75a30d6e439f508e551c200";
    hash = "sha256-MNqdZ3e3iV/TytmLVtJ33Aa+RoPDNLTwj1zgF276Gac=";
    finalImageName = "ghcr.io/idanreed/caddy-cloudflare";
    finalImageTag = "2.11.2";
  };
  "ghcr_io_immich-app_immich-machine-learning_v3_1_0" = {
    composeRef = "ghcr.io/immich-app/immich-machine-learning:v3.1.0";
    imageName = "ghcr.io/immich-app/immich-machine-learning";
    imageDigest = "sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e";
    hash = "sha256-sidStRBLUqvW7KNqgr08e3uNXNpghY33vL5bTBb+8UI=";
    finalImageName = "ghcr.io/immich-app/immich-machine-learning";
    finalImageTag = "v3.1.0";
  };
  "ghcr_io_immich-app_immich-server_v3_1_0" = {
    composeRef = "ghcr.io/immich-app/immich-server:v3.1.0";
    imageName = "ghcr.io/immich-app/immich-server";
    imageDigest = "sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb";
    hash = "sha256-kQnTcmK0Mn2YaM4HBmT3zpDbPp3n09gtMwki+j1QjwI=";
    finalImageName = "ghcr.io/immich-app/immich-server";
    finalImageTag = "v3.1.0";
  };
  "ghcr_io_immich-app_postgres_17-vectorchord1_1_1" = {
    composeRef = "ghcr.io/immich-app/postgres:17-vectorchord1.1.1";
    imageName = "ghcr.io/immich-app/postgres";
    imageDigest = "sha256:3ea13db44f1116042032ec638979eae2dbd4f2419c7d2e134fbe308a534cb054";
    hash = "sha256-x7kt2Ts/NQy0jhed6r5GTQyRI310U22/AeltD3zd2no=";
    finalImageName = "ghcr.io/immich-app/postgres";
    finalImageTag = "17-vectorchord1.1.1";
  };
  "ghcr_io_karakeep-app_karakeep_0_33_2" = {
    composeRef = "ghcr.io/karakeep-app/karakeep:0.33.2";
    imageName = "ghcr.io/karakeep-app/karakeep";
    imageDigest = "sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c";
    hash = "sha256-HzE4SHDwIEdB7/4v61MzyjjWhDc5gY7DSd2+WqDLPbo=";
    finalImageName = "ghcr.io/karakeep-app/karakeep";
    finalImageTag = "0.33.2";
  };
  "ghcr_io_karakeep-app_karakeep-chrome_151_0_7922_47-r1" = {
    composeRef = "ghcr.io/karakeep-app/karakeep-chrome:151.0.7922.47-r1";
    imageName = "ghcr.io/karakeep-app/karakeep-chrome";
    imageDigest = "sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7";
    hash = "sha256-ypbGcOEpuUSZoEZr1x0keH+WCBDOz0HiH0iqKhcJQlI=";
    finalImageName = "ghcr.io/karakeep-app/karakeep-chrome";
    finalImageTag = "151.0.7922.47-r1";
  };
  "ghcr_io_paperless-ngx_paperless-ngx_2_20" = {
    composeRef = "ghcr.io/paperless-ngx/paperless-ngx:2.20";
    imageName = "ghcr.io/paperless-ngx/paperless-ngx";
    imageDigest = "sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f";
    hash = "sha256-g/jYJPVb1lPPP9jVsQnZoLKKvvjXpqRlZYxwKrMBBJQ=";
    finalImageName = "ghcr.io/paperless-ngx/paperless-ngx";
    finalImageTag = "2.20";
  };
  "ghcr_io_seerr-team_seerr_v3_4_1" = {
    composeRef = "ghcr.io/seerr-team/seerr:v3.4.1";
    imageName = "ghcr.io/seerr-team/seerr";
    imageDigest = "sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1";
    hash = "sha256-ey9wDtv/m/y1+EbGk/RmgZhjlt4VLpLDbm6AGcSg60Y=";
    finalImageName = "ghcr.io/seerr-team/seerr";
    finalImageTag = "v3.4.1";
  };
  "ghcr_io_silverbulletmd_silverbullet_2_9_0" = {
    composeRef = "ghcr.io/silverbulletmd/silverbullet:2.9.0";
    imageName = "ghcr.io/silverbulletmd/silverbullet";
    imageDigest = "sha256:82e76a800920370d83e2f50c6946d3c420954b0bd417dbb96f7911513fa05620";
    hash = "sha256-iTd2ZQ8W6KsbCcBPPXg3mKpLhKuceji6ol2P2XOUI2s=";
    finalImageName = "ghcr.io/silverbulletmd/silverbullet";
    finalImageTag = "2.9.0";
  };
  "ghcr_io_sysadminsmedia_homebox_0_26_2" = {
    composeRef = "ghcr.io/sysadminsmedia/homebox:0.26.2";
    imageName = "ghcr.io/sysadminsmedia/homebox";
    imageDigest = "sha256:b1ad7e3c63f732a5f6daa466e8116be4f545b3b120383a64dcb62beb00a660cc";
    hash = "sha256-0PZjSugWBizjx95TAt17OI13ApGxkFGVFzDJBfTW/Zo=";
    finalImageName = "ghcr.io/sysadminsmedia/homebox";
    finalImageTag = "0.26.2";
  };
  "ghcr_io_tandoorrecipes_recipes_2_6_13" = {
    composeRef = "ghcr.io/tandoorrecipes/recipes:2.6.13";
    imageName = "ghcr.io/tandoorrecipes/recipes";
    imageDigest = "sha256:f6c58afdea7a721d079ebd6ee5483f2c9da77dd1e709e16d60a82c218e80a451";
    hash = "sha256-UIEIe0mzJ+pAKuGlubmLYl/NYM1zNkGjoA9OzWg5Su8=";
    finalImageName = "ghcr.io/tandoorrecipes/recipes";
    finalImageTag = "2.6.13";
  };
  "ghcr_io_twin_gatus_v5_36_0" = {
    composeRef = "ghcr.io/twin/gatus:v5.36.0";
    imageName = "ghcr.io/twin/gatus";
    imageDigest = "sha256:c5f210d095fa78e6efaa20ffeb14803f2ba4f10615e16a6d12087697149617f0";
    hash = "sha256-phSPgKeBnZyn4DKd6wR++JKsnJRnDsTlguDNzKQvLHg=";
    finalImageName = "ghcr.io/twin/gatus";
    finalImageTag = "v5.36.0";
  };
  "ghcr_io_windmill-labs_windmill_1_798_1" = {
    composeRef = "ghcr.io/windmill-labs/windmill:1.798.1";
    imageName = "ghcr.io/windmill-labs/windmill";
    imageDigest = "sha256:155a4da7ac27d75cf5349c56f59bfb7c26dc832ab23b7d373a22a91df43c6d9b";
    hash = "sha256-mOZNLrEZdgVZ1f/y6Yy8dRK0jhK96cqGnL0r6622F6E=";
    finalImageName = "ghcr.io/windmill-labs/windmill";
    finalImageTag = "1.798.1";
  };
  "ghostfolio_ghostfolio_3_65_0" = {
    composeRef = "ghostfolio/ghostfolio:3.65.0";
    imageName = "ghostfolio/ghostfolio";
    imageDigest = "sha256:5762d47097bb30f6e8c51a1a0ebd9a39798631b512d8a78223bcfe68202e5286";
    hash = "sha256-jY8ToVl2xU/7IA11O3Gp/dMc+QWKAj0BZ0tUDHYrsu0=";
    finalImageName = "ghostfolio/ghostfolio";
    finalImageTag = "3.65.0";
  };
  "glanceapp_glance_v0_8_5" = {
    composeRef = "glanceapp/glance:v0.8.5";
    imageName = "glanceapp/glance";
    imageDigest = "sha256:32ab73d80f2b8b5fb0735b0431deb36b93fbb6b2fb43592449b0178c8b83e350";
    hash = "sha256-QgJUznGWUhjHGk2e8I3KkbpAaelHDtovfMOssLlwwr8=";
    finalImageName = "glanceapp/glance";
    finalImageTag = "v0.8.5";
  };
  "gotenberg_gotenberg_8_31" = {
    composeRef = "gotenberg/gotenberg:8.31";
    imageName = "gotenberg/gotenberg";
    imageDigest = "sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3";
    hash = "sha256-atlBNyHFkLCx4Eg9zeVkIesDq2SZPJuNiCWEH++MR/g=";
    finalImageName = "gotenberg/gotenberg";
    finalImageTag = "8.31";
  };
  "grafana_alloy_v1_19_2" = {
    composeRef = "grafana/alloy:v1.19.2";
    imageName = "grafana/alloy";
    imageDigest = "sha256:b8ec653c44235fbe910879145dac3597d66b0aaecf60bcbbe82580767771a839";
    hash = "sha256-4H7bR6t4jSPuV4LNLBOwA8XCPMr2x281caZLbFnMJRI=";
    finalImageName = "grafana/alloy";
    finalImageTag = "v1.19.2";
  };
  "grafana_grafana_13_2_0" = {
    composeRef = "grafana/grafana:13.2.0";
    imageName = "grafana/grafana";
    imageDigest = "sha256:3fd54ae1214669f8355f065ec9f6445d5279a3d77095ab048ca045685272429b";
    hash = "sha256-2qQydw2ShBZxEZjXXeeq1SaS8+MSHnHWTCxDNQZ95i8=";
    finalImageName = "grafana/grafana";
    finalImageTag = "13.2.0";
  };
  "grafana_loki_3_7_7" = {
    composeRef = "grafana/loki:3.7.7";
    imageName = "grafana/loki";
    imageDigest = "sha256:d70e4659623f3e109af669cae76fe2a5dd5be54e2298fe8aed380d982fbc2500";
    hash = "sha256-6t3JDDRrvT/6RQ/m+eoHdOxWr3LZ6JlsKKPDPGPD128=";
    finalImageName = "grafana/loki";
    finalImageTag = "3.7.7";
  };
  "henrygd_beszel_0_18_8" = {
    composeRef = "henrygd/beszel:0.18.8";
    imageName = "henrygd/beszel";
    imageDigest = "sha256:4c51486968efa0b0a702c1b0967966a2e06fb250b7418f3072d2488faea27c51";
    hash = "sha256-TbFht12yqGMEEPUpX0MyVFFFAI4HW/lbtmUhLOSs3qI=";
    finalImageName = "henrygd/beszel";
    finalImageTag = "0.18.8";
  };
  "henrygd_beszel-agent_0_18_8" = {
    composeRef = "henrygd/beszel-agent:0.18.8";
    imageName = "henrygd/beszel-agent";
    imageDigest = "sha256:3b1939746690e423072b4a99bf4c4af6dd9562a68978a33738a3c4a4cc000c39";
    hash = "sha256-1xsL/szZbEhwsYmLWtkqBgqgPrxuwzhbvpEEaZVPN9g=";
    finalImageName = "henrygd/beszel-agent";
    finalImageTag = "0.18.8";
  };
  "jellyfin_jellyfin_10_11_11" = {
    composeRef = "jellyfin/jellyfin:10.11.11";
    imageName = "jellyfin/jellyfin";
    imageDigest = "sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db";
    hash = "sha256-F9lEzgiYpriAIktSR1TB4D7hkfSCSzqRuYXevc7X9H0=";
    finalImageName = "jellyfin/jellyfin";
    finalImageTag = "10.11.11";
  };
  "jvmilazz0_kavita_0_9_1" = {
    composeRef = "jvmilazz0/kavita:0.9.1";
    imageName = "jvmilazz0/kavita";
    imageDigest = "sha256:454f2a77ac740b70c58cc7300a11122fc9ce7b7e2161ef5b0d1df8f81067cc85";
    hash = "sha256-vp4RRSKrG6qCeAlFyT58rbOyWHPzMbtAxP1VigzgxwY=";
    finalImageName = "jvmilazz0/kavita";
    finalImageTag = "0.9.1";
  };
  "lscr_io_linuxserver_bazarr_1_6_0" = {
    composeRef = "lscr.io/linuxserver/bazarr:1.6.0";
    imageName = "lscr.io/linuxserver/bazarr";
    imageDigest = "sha256:3a820372f19fcb2981ea19fe4b5382934d67414afaba974bce831ddda0a64a02";
    hash = "sha256-ppbFf06Lj8bCjXfgTMFwffy0LN41Kzcwbbky5i3PEng=";
    finalImageName = "lscr.io/linuxserver/bazarr";
    finalImageTag = "1.6.0";
  };
  "lscr_io_linuxserver_bookstack_version-v26_05_4" = {
    composeRef = "lscr.io/linuxserver/bookstack:version-v26.05.4";
    imageName = "lscr.io/linuxserver/bookstack";
    imageDigest = "sha256:90a3df3108fe4471a9ed89625020cc321c5354255900c34309727320f2e65367";
    hash = "sha256-DTZuYhZA8YTADxIP+9AenU+IZdqgLjIIGGvMWJjjyxw=";
    finalImageName = "lscr.io/linuxserver/bookstack";
    finalImageTag = "version-v26.05.4";
  };
  "lscr_io_linuxserver_prowlarr_2_5_2" = {
    composeRef = "lscr.io/linuxserver/prowlarr:2.5.2";
    imageName = "lscr.io/linuxserver/prowlarr";
    imageDigest = "sha256:ab91301778251f82a31bbfc87f0497376d59e84439d9a1ceff6a61d594d1e3d7";
    hash = "sha256-trhuZM+usGIDVAv4K1qcitKrxHYJdcyBfar3mHLfQpQ=";
    finalImageName = "lscr.io/linuxserver/prowlarr";
    finalImageTag = "2.5.2";
  };
  "lscr_io_linuxserver_qbittorrent_5_2_3" = {
    composeRef = "lscr.io/linuxserver/qbittorrent:5.2.3";
    imageName = "lscr.io/linuxserver/qbittorrent";
    imageDigest = "sha256:a00b6a597a3832a1814cde0ef60abc55c94644f3f80902c3432f6af6de8d4a96";
    hash = "sha256-WHA70XvYD+gcbakTnsYgKiK7HJ1o2tC4d/6y1b0xvIA=";
    finalImageName = "lscr.io/linuxserver/qbittorrent";
    finalImageTag = "5.2.3";
  };
  "lscr_io_linuxserver_radarr_6_3_0" = {
    composeRef = "lscr.io/linuxserver/radarr:6.3.0";
    imageName = "lscr.io/linuxserver/radarr";
    imageDigest = "sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438";
    hash = "sha256-6pkx0xLk7AFTw8hWBckUPKfgGZbNTLDk67xneOmMjP0=";
    finalImageName = "lscr.io/linuxserver/radarr";
    finalImageTag = "6.3.0";
  };
  "lscr_io_linuxserver_sonarr_4_0_19" = {
    composeRef = "lscr.io/linuxserver/sonarr:4.0.19";
    imageName = "lscr.io/linuxserver/sonarr";
    imageDigest = "sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224";
    hash = "sha256-TbKMUIDefITrsAP9mIdP1T7hb0iCYyXXmAtXoAsQnmI=";
    finalImageName = "lscr.io/linuxserver/sonarr";
    finalImageTag = "4.0.19";
  };
  "mariadb_11_8_9" = {
    composeRef = "mariadb:11.8.9";
    imageName = "mariadb";
    imageDigest = "sha256:2439dcd7d14010ecd1ff7a4e1c5abe8e208c34fe35290744deeeaac3569043c3";
    hash = "sha256-RGRQqypV9iJ7mr9LpoOSZ6pud9EO6juZq2UM3190T14=";
    finalImageName = "mariadb";
    finalImageTag = "11.8.9";
  };
  "mysql_8_4_6" = {
    composeRef = "mysql:8.4.6";
    imageName = "mysql";
    imageDigest = "sha256:869218921e61d6c3c89820955d63cca42971f0e3e6c1e2792247bbd944ebc6e9";
    hash = "sha256-P0xvP10x/5ebvehT5WsJ690N1pP2jASk7CUFFvNpE6w=";
    finalImageName = "mysql";
    finalImageTag = "8.4.6";
  };
  "nginx_1_30_4-alpine" = {
    composeRef = "nginx:1.30.4-alpine";
    imageName = "nginx";
    imageDigest = "sha256:97d490c12ba55b4946b01546d1c3ed324e8d41ab1c9fcb2a616aa470620e5b46";
    hash = "sha256-pznF0twPb4as4Q5ju2alGn/ZCzAHfBh9APsYdo8yw5I=";
    finalImageName = "nginx";
    finalImageTag = "1.30.4-alpine";
  };
  "onlyoffice_docspace_3_7_2" = {
    composeRef = "onlyoffice/docspace:3.7.2";
    imageName = "onlyoffice/docspace";
    imageDigest = "sha256:0002035c86a568f4798ac46b622769434b9317e2a429a7fa7ce503abc25cfc64";
    hash = "sha256-ddKtXCbIQvI4Y31mme2/Zy1syonrRy0oUDT51hkOZjY=";
    finalImageName = "onlyoffice/docspace";
    finalImageTag = "3.7.2";
  };
  "onlyoffice_documentserver_9_4_0" = {
    composeRef = "onlyoffice/documentserver:9.4.0";
    imageName = "onlyoffice/documentserver";
    imageDigest = "sha256:e3da62a847b9a5d51a11f73cfea1d9c13c3be3809614490d4edddcf01dcf919b";
    hash = "sha256-9a6jXW5S4eQTKMvYYvzg4k8BNpMnxqP3cyN+QpF6VHs=";
    finalImageName = "onlyoffice/documentserver";
    finalImageTag = "9.4.0";
  };
  "outlinewiki_outline_1_9_2" = {
    composeRef = "outlinewiki/outline:1.9.2";
    imageName = "outlinewiki/outline";
    imageDigest = "sha256:32d76719c378931dd65d93945930ca380d8376a0337d98a991fcc12b266f33cf";
    hash = "sha256-fdvcowN3b9MMsBcp9SEib0Um8aO1GjoRetObQsUe/Ag=";
    finalImageName = "outlinewiki/outline";
    finalImageTag = "1.9.2";
  };
  "owlplanner_owldocker_2026_8_29" = {
    composeRef = "owlplanner/owldocker:2026.8.29";
    imageName = "owlplanner/owldocker";
    imageDigest = "sha256:ea7088e91fcd4a25b3a8edecb9c90bfa500d02640bb2ebfc7fc527168d9c5702";
    hash = "sha256-VqviYs9sswL8e/01/ARv0cxs00232qy5A71x0fw3UZo=";
    finalImageName = "owlplanner/owldocker";
    finalImageTag = "2026.8.29";
  };
  "postgis_postgis_17-3_5-alpine" = {
    composeRef = "postgis/postgis:17-3.5-alpine";
    imageName = "postgis/postgis";
    imageDigest = "sha256:894f570c0cf0664ed5576a8fd5d5bfb8fb1b19d592885b686c3a88c8bd90c41f";
    hash = "sha256-maeMcu77S+wRSy5KgwqOzYFNm3giUfKrodxXHxZQBHI=";
    finalImageName = "postgis/postgis";
    finalImageTag = "17-3.5-alpine";
  };
  "postgres_16_13-alpine" = {
    composeRef = "postgres:16.13-alpine";
    imageName = "postgres";
    imageDigest = "sha256:4e6e670bb069649261c9c18031f0aded7bb249a5b6664ddec29c013a89310d50";
    hash = "sha256-07iy6tVD2L+3eoZM7wzqBr69UVzfr9suCT3uK13NL+o=";
    finalImageName = "postgres";
    finalImageTag = "16.13-alpine";
  };
  "postgres_17_9-alpine" = {
    composeRef = "postgres:17.9-alpine";
    imageName = "postgres";
    imageDigest = "sha256:c7526c0f6c3f30260a563d7bcf8ad778effac59a44f8ffa86678c35418338609";
    hash = "sha256-wUfbwIV1ZCshwFfp+9hZN9LuaO3VPz365jHceDFEO/c=";
    finalImageName = "postgres";
    finalImageTag = "17.9-alpine";
  };
  "python_3_13-alpine" = {
    composeRef = "python:3.13-alpine";
    imageName = "python";
    imageDigest = "sha256:540c7d91f98ff6880174c40e99067bf5941eb54d818a7a5e094d188b196a934d";
    hash = "sha256-VezYqm4Tbx9aFHtkIb7RI/cx5uRz0iVQTHEmv7GO3NY=";
    finalImageName = "python";
    finalImageTag = "3.13-alpine";
  };
  "qmcgaw_gluetun_v3_41_3" = {
    composeRef = "qmcgaw/gluetun:v3.41.3";
    imageName = "qmcgaw/gluetun";
    imageDigest = "sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027";
    hash = "sha256-ao1WZ8MYI/gXIqNLYQW7GLB8tmWqExvhAlJjXCPXp1o=";
    finalImageName = "qmcgaw/gluetun";
    finalImageTag = "v3.41.3";
  };
  "redis_7_4-alpine" = {
    composeRef = "redis:7.4-alpine";
    imageName = "redis";
    imageDigest = "sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf";
    hash = "sha256-SAxWBbQAa0iI5ehP2eImFgfOHjRlm4fxLJSiKZx6/Q4=";
    finalImageName = "redis";
    finalImageTag = "7.4-alpine";
  };
  "syncthing_syncthing_2_1_3" = {
    composeRef = "syncthing/syncthing:2.1.3";
    imageName = "syncthing/syncthing";
    imageDigest = "sha256:8c8ff37ab6aa8be23b700648a90fa9412e214852e9fd6ea8477c8334792daec0";
    hash = "sha256-cimA9IBFrBGIy49RoQKApPdyXlgSPC8m30hPyL6yuLo=";
    finalImageName = "syncthing/syncthing";
    finalImageTag = "2.1.3";
  };
  "valkey_valkey_9_1-alpine" = {
    composeRef = "valkey/valkey:9.1-alpine";
    imageName = "valkey/valkey";
    imageDigest = "sha256:15568b9cb7eb67f4aed4de018c23f13d344e0e6437b31fe8fb8823dc81ebb3a9";
    hash = "sha256-fF88phuBt12Y0dUssOi/QFWSmm4oZPyKwg9R0XKW9Pk=";
    finalImageName = "valkey/valkey";
    finalImageTag = "9.1-alpine";
  };
  "vaultwarden_server_1_37_2" = {
    composeRef = "vaultwarden/server:1.37.2";
    imageName = "vaultwarden/server";
    imageDigest = "sha256:094b5689ed81549bd293418395c7cf495ae9d960fc2d4928cef2083ef913d912";
    hash = "sha256-eZu7Be9lm/hCvqkG+oZ7fyP+YTBG3osSeXWrIZiV/2k=";
    finalImageName = "vaultwarden/server";
    finalImageTag = "1.37.2";
  };
  "wger_server_2_6" = {
    composeRef = "wger/server:2.6";
    imageName = "wger/server";
    imageDigest = "sha256:997ead43aabdcd67d054f933e07d2b23875f01bf43271a267cb7796925ca27c4";
    hash = "sha256-qC0sKiYeoiGCCXSLRD7bTDQj4wiQpd6kgsZhLqunP2E=";
    finalImageName = "wger/server";
    finalImageTag = "2.6";
  };
  _unresolved = [
  ];
  _skipped = [
  ];
}
