# GENERATED by tests/update-images.sh — do not edit by hand.
#
# Maps a compose `image:` reference to a content-addressed pin that
# dockerTools.pullImage can fetch offline. `composeRef` is the string as it
# appears in the compose file; the suites key off it so the drift lint can
# compare the two.
{
  "alpine_3_21" = {
    composeRef = "alpine:3.21";
    imageName = "alpine";
    imageDigest = "sha256:48b0309ca019d89d40f670aa1bc06e426dc0931948452e8491e3d65087abc07d";
    hash = "sha256-LF7w479+22OQjiScUf+wSKIK12isourh11CrfiztdzI=";
    finalImageName = "alpine";
    finalImageTag = "3.21";
  };
  "apache_tika_3_3_0_0" = {
    composeRef = "apache/tika:3.3.0.0";
    imageName = "apache/tika";
    imageDigest = "sha256:2a565f1ea1290bdcb74a7d35957d16a989ed44ef98790dcdcc28121d728fa583";
    hash = "sha256-fWuqnkv542d0oMcRqpEtis8sFbmqO6VQ9RtU4dsg+g4=";
    finalImageName = "apache/tika";
    finalImageTag = "3.3.0.0";
  };
  "binwiederhier_ntfy_v2_11_0" = {
    composeRef = "binwiederhier/ntfy:v2.11.0";
    imageName = "binwiederhier/ntfy";
    imageDigest = "sha256:4a7d0f0adc6d5d9fc36e64ab55ef676e76e124a2bdd50ce115b6d9c1c7430294";
    hash = "sha256-YyFHylsrqo9yYDFOgnbn9dJhkB1Ol6Te4mX0N1fRD2s=";
    finalImageName = "binwiederhier/ntfy";
    finalImageTag = "v2.11.0";
  };
  "clamav_clamav_1_5" = {
    composeRef = "clamav/clamav:1.5";
    imageName = "clamav/clamav";
    imageDigest = "sha256:0e85467cb0d6e7d860a45035707741cd5ffc032ffefc6002a3510c75b6d07027";
    hash = "sha256-mUR3XaloyMm6DTxlGB/BBLfTlDQISAc4yfmkoRMM1/Y=";
    finalImageName = "clamav/clamav";
    finalImageTag = "1.5";
  };
  "codeberg_org_forgejo_forgejo_16_0" = {
    composeRef = "codeberg.org/forgejo/forgejo:16.0";
    imageName = "codeberg.org/forgejo/forgejo";
    imageDigest = "sha256:7c4e1db440be7b2ca685b49d0d7864cdd78e92431f531bf7893659def8200fc5";
    hash = "sha256-hXuu9eeWYGfUba1aFChZcrtyw8Kpz3drDKnXv3Okp8Q=";
    finalImageName = "codeberg.org/forgejo/forgejo";
    finalImageTag = "16.0";
  };
  "garethgeorge_backrest_v1_9_1" = {
    composeRef = "garethgeorge/backrest:v1.9.1";
    imageName = "garethgeorge/backrest";
    imageDigest = "sha256:96feace1c73a6869ca581348c1ecc35dfeab39be9b0e6c9aaabe4bc7889435be";
    hash = "sha256-lxt64sZTGpYrxVZFPp4jlbl8ai/bd9C6i2h835jyO74=";
    finalImageName = "garethgeorge/backrest";
    finalImageTag = "v1.9.1";
  };
  "ghcr_io_alam00000_bentopdf_1_16_1" = {
    composeRef = "ghcr.io/alam00000/bentopdf:1.16.1";
    imageName = "ghcr.io/alam00000/bentopdf";
    imageDigest = "sha256:d98223eb82661a9f6624a813ed7fc44ad4f80e761e24116a721e1cd891ac8c3f";
    hash = "sha256-XC2oqDa8p50Ck1u92JqHX/Pm//94OOJmiTEdOWHEAU4=";
    finalImageName = "ghcr.io/alam00000/bentopdf";
    finalImageTag = "1.16.1";
  };
  "ghcr_io_civilblur_mazanoke_v1_1_5" = {
    composeRef = "ghcr.io/civilblur/mazanoke:v1.1.5";
    imageName = "ghcr.io/civilblur/mazanoke";
    imageDigest = "sha256:e43dc48de575b7a032bbefd96b890d69c1f141417e43d5d096469aa1398711d6";
    hash = "sha256-4Jcx9/SR4/FGifTh1SBWzD2JKueaysmv4ndDQdcwmE0=";
    finalImageName = "ghcr.io/civilblur/mazanoke";
    finalImageTag = "v1.1.5";
  };
  "ghcr_io_cleanuparr_cleanuparr_2_10_5" = {
    composeRef = "ghcr.io/cleanuparr/cleanuparr:2.10.5";
    imageName = "ghcr.io/cleanuparr/cleanuparr";
    imageDigest = "sha256:c7cd53ad559a67147637de3d825f66ef6e6a5498490b73f49c6e4d72f13bed76";
    hash = "sha256-nDwB4DkBKrnJM2IVTDZSzTroCBqkkmfSyEtVRek4dpE=";
    finalImageName = "ghcr.io/cleanuparr/cleanuparr";
    finalImageTag = "2.10.5";
  };
  "ghcr_io_dictionarry-hub_profilarr_2_2_0" = {
    composeRef = "ghcr.io/dictionarry-hub/profilarr:2.2.0";
    imageName = "ghcr.io/dictionarry-hub/profilarr";
    imageDigest = "sha256:ddcdd0f340043c2ec0a85ca74b9a6be9be42b1c0288c75fc36a26a43f695860b";
    hash = "sha256-mWa8eAFbR/oqmJGYBs1QjbNoRLWHJud4Gfr651Fkur0=";
    finalImageName = "ghcr.io/dictionarry-hub/profilarr";
    finalImageTag = "2.2.0";
  };
  "ghcr_io_getarcaneapp_arcane_v1_17_4" = {
    composeRef = "ghcr.io/getarcaneapp/arcane:v1.17.4";
    imageName = "ghcr.io/getarcaneapp/arcane";
    imageDigest = "sha256:97492274e59c9f822a9c49d67981912b81919c0edad6094e496fa3507348082e";
    hash = "sha256-mqBArBFkyP5M6KOsb2RX974vPpDh9W/RtxoIpmt7IcQ=";
    finalImageName = "ghcr.io/getarcaneapp/arcane";
    finalImageTag = "v1.17.4";
  };
  "ghcr_io_goauthentik_server_2026_5_6" = {
    composeRef = "ghcr.io/goauthentik/server:2026.5.6";
    imageName = "ghcr.io/goauthentik/server";
    imageDigest = "sha256:ed120caf710ccf82ef0026f0bc74e51615bc95ebff228a7a2d6fc60c441c3868";
    hash = "sha256-58hlqmnlLLaIz5S1EBHayHUOSoiQmULhe76jnAiNl/k=";
    finalImageName = "ghcr.io/goauthentik/server";
    finalImageTag = "2026.5.6";
  };
  "ghcr_io_idanreed_caddy-cloudflare_2_11_2" = {
    composeRef = "ghcr.io/idanreed/caddy-cloudflare:2.11.2";
    imageName = "ghcr.io/idanreed/caddy-cloudflare";
    imageDigest = "sha256:a96289a08e6a1ba5dccc650a00b86083c0629329e75a30d6e439f508e551c200";
    hash = "sha256-MNqdZ3e3iV/TytmLVtJ33Aa+RoPDNLTwj1zgF276Gac=";
    finalImageName = "ghcr.io/idanreed/caddy-cloudflare";
    finalImageTag = "2.11.2";
  };
  "ghcr_io_immich-app_immich-machine-learning_v3_1_0" = {
    composeRef = "ghcr.io/immich-app/immich-machine-learning:v3.1.0";
    imageName = "ghcr.io/immich-app/immich-machine-learning";
    imageDigest = "sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e";
    hash = "sha256-sidStRBLUqvW7KNqgr08e3uNXNpghY33vL5bTBb+8UI=";
    finalImageName = "ghcr.io/immich-app/immich-machine-learning";
    finalImageTag = "v3.1.0";
  };
  "ghcr_io_immich-app_immich-server_v3_1_0" = {
    composeRef = "ghcr.io/immich-app/immich-server:v3.1.0";
    imageName = "ghcr.io/immich-app/immich-server";
    imageDigest = "sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb";
    hash = "sha256-kQnTcmK0Mn2YaM4HBmT3zpDbPp3n09gtMwki+j1QjwI=";
    finalImageName = "ghcr.io/immich-app/immich-server";
    finalImageTag = "v3.1.0";
  };
  "ghcr_io_immich-app_postgres_17-vectorchord1_1_1" = {
    composeRef = "ghcr.io/immich-app/postgres:17-vectorchord1.1.1";
    imageName = "ghcr.io/immich-app/postgres";
    imageDigest = "sha256:3ea13db44f1116042032ec638979eae2dbd4f2419c7d2e134fbe308a534cb054";
    hash = "sha256-x7kt2Ts/NQy0jhed6r5GTQyRI310U22/AeltD3zd2no=";
    finalImageName = "ghcr.io/immich-app/postgres";
    finalImageTag = "17-vectorchord1.1.1";
  };
  "ghcr_io_paperless-ngx_paperless-ngx_2_20" = {
    composeRef = "ghcr.io/paperless-ngx/paperless-ngx:2.20";
    imageName = "ghcr.io/paperless-ngx/paperless-ngx";
    imageDigest = "sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f";
    hash = "sha256-g/jYJPVb1lPPP9jVsQnZoLKKvvjXpqRlZYxwKrMBBJQ=";
    finalImageName = "ghcr.io/paperless-ngx/paperless-ngx";
    finalImageTag = "2.20";
  };
  "ghcr_io_seerr-team_seerr_v3_4_1" = {
    composeRef = "ghcr.io/seerr-team/seerr:v3.4.1";
    imageName = "ghcr.io/seerr-team/seerr";
    imageDigest = "sha256:f4768de5f616248d723e05891f3345a1402123775d03bf0890dbfedc0831bda1";
    hash = "sha256-ey9wDtv/m/y1+EbGk/RmgZhjlt4VLpLDbm6AGcSg60Y=";
    finalImageName = "ghcr.io/seerr-team/seerr";
    finalImageTag = "v3.4.1";
  };
  "gotenberg_gotenberg_8_31" = {
    composeRef = "gotenberg/gotenberg:8.31";
    imageName = "gotenberg/gotenberg";
    imageDigest = "sha256:f0d86e8a1dbc7b33a5a65cb251d02bb271a48ffa989da3feb5ed7d954fe4d4b3";
    hash = "sha256-atlBNyHFkLCx4Eg9zeVkIesDq2SZPJuNiCWEH++MR/g=";
    finalImageName = "gotenberg/gotenberg";
    finalImageTag = "8.31";
  };
  "jellyfin_jellyfin_10_11_11" = {
    composeRef = "jellyfin/jellyfin:10.11.11";
    imageName = "jellyfin/jellyfin";
    imageDigest = "sha256:aefb67e6a7ff1debdd154a78a7bbb780fd0c873d8639210a7f6a2016ad2b35db";
    hash = "sha256-F9lEzgiYpriAIktSR1TB4D7hkfSCSzqRuYXevc7X9H0=";
    finalImageName = "jellyfin/jellyfin";
    finalImageTag = "10.11.11";
  };
  "lscr_io_linuxserver_bazarr_1_6_0" = {
    composeRef = "lscr.io/linuxserver/bazarr:1.6.0";
    imageName = "lscr.io/linuxserver/bazarr";
    imageDigest = "sha256:3a820372f19fcb2981ea19fe4b5382934d67414afaba974bce831ddda0a64a02";
    hash = "sha256-ppbFf06Lj8bCjXfgTMFwffy0LN41Kzcwbbky5i3PEng=";
    finalImageName = "lscr.io/linuxserver/bazarr";
    finalImageTag = "1.6.0";
  };
  "lscr_io_linuxserver_prowlarr_2_5_2" = {
    composeRef = "lscr.io/linuxserver/prowlarr:2.5.2";
    imageName = "lscr.io/linuxserver/prowlarr";
    imageDigest = "sha256:ab91301778251f82a31bbfc87f0497376d59e84439d9a1ceff6a61d594d1e3d7";
    hash = "sha256-trhuZM+usGIDVAv4K1qcitKrxHYJdcyBfar3mHLfQpQ=";
    finalImageName = "lscr.io/linuxserver/prowlarr";
    finalImageTag = "2.5.2";
  };
  "lscr_io_linuxserver_qbittorrent_5_2_3" = {
    composeRef = "lscr.io/linuxserver/qbittorrent:5.2.3";
    imageName = "lscr.io/linuxserver/qbittorrent";
    imageDigest = "sha256:a00b6a597a3832a1814cde0ef60abc55c94644f3f80902c3432f6af6de8d4a96";
    hash = "sha256-WHA70XvYD+gcbakTnsYgKiK7HJ1o2tC4d/6y1b0xvIA=";
    finalImageName = "lscr.io/linuxserver/qbittorrent";
    finalImageTag = "5.2.3";
  };
  "lscr_io_linuxserver_radarr_6_3_0" = {
    composeRef = "lscr.io/linuxserver/radarr:6.3.0";
    imageName = "lscr.io/linuxserver/radarr";
    imageDigest = "sha256:119aaa4a4f7349bcd2a136c5373a0d7925b5479915c7dfe0c0ad352db2a6d438";
    hash = "sha256-6pkx0xLk7AFTw8hWBckUPKfgGZbNTLDk67xneOmMjP0=";
    finalImageName = "lscr.io/linuxserver/radarr";
    finalImageTag = "6.3.0";
  };
  "lscr_io_linuxserver_sonarr_4_0_19" = {
    composeRef = "lscr.io/linuxserver/sonarr:4.0.19";
    imageName = "lscr.io/linuxserver/sonarr";
    imageDigest = "sha256:c19aa4ecdf03d73e1d5c901da33744cb7eb4d921f89bafed1ca264601d7fa224";
    hash = "sha256-TbKMUIDefITrsAP9mIdP1T7hb0iCYyXXmAtXoAsQnmI=";
    finalImageName = "lscr.io/linuxserver/sonarr";
    finalImageTag = "4.0.19";
  };
  "postgres_16_13-alpine" = {
    composeRef = "postgres:16.13-alpine";
    imageName = "postgres";
    imageDigest = "sha256:4e6e670bb069649261c9c18031f0aded7bb249a5b6664ddec29c013a89310d50";
    hash = "sha256-07iy6tVD2L+3eoZM7wzqBr69UVzfr9suCT3uK13NL+o=";
    finalImageName = "postgres";
    finalImageTag = "16.13-alpine";
  };
  "postgres_17_9-alpine" = {
    composeRef = "postgres:17.9-alpine";
    imageName = "postgres";
    imageDigest = "sha256:c7526c0f6c3f30260a563d7bcf8ad778effac59a44f8ffa86678c35418338609";
    hash = "sha256-wUfbwIV1ZCshwFfp+9hZN9LuaO3VPz365jHceDFEO/c=";
    finalImageName = "postgres";
    finalImageTag = "17.9-alpine";
  };
  "python_3_13-alpine" = {
    composeRef = "python:3.13-alpine";
    imageName = "python";
    imageDigest = "sha256:540c7d91f98ff6880174c40e99067bf5941eb54d818a7a5e094d188b196a934d";
    hash = "sha256-VezYqm4Tbx9aFHtkIb7RI/cx5uRz0iVQTHEmv7GO3NY=";
    finalImageName = "python";
    finalImageTag = "3.13-alpine";
  };
  "qmcgaw_gluetun_v3_41_3" = {
    composeRef = "qmcgaw/gluetun:v3.41.3";
    imageName = "qmcgaw/gluetun";
    imageDigest = "sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027";
    hash = "sha256-ao1WZ8MYI/gXIqNLYQW7GLB8tmWqExvhAlJjXCPXp1o=";
    finalImageName = "qmcgaw/gluetun";
    finalImageTag = "v3.41.3";
  };
  "redis_7_4-alpine" = {
    composeRef = "redis:7.4-alpine";
    imageName = "redis";
    imageDigest = "sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf";
    hash = "sha256-SAxWBbQAa0iI5ehP2eImFgfOHjRlm4fxLJSiKZx6/Q4=";
    finalImageName = "redis";
    finalImageTag = "7.4-alpine";
  };
  "valkey_valkey_9_1-alpine" = {
    composeRef = "valkey/valkey:9.1-alpine";
    imageName = "valkey/valkey";
    imageDigest = "sha256:de31910896150d5e754a07d57d227cfdde4e258ddd0d1aa4607f2d2f95843715";
    hash = "sha256-MNqkpCQqn11UE8bvqGeBTsTpkLeIhWV+7UnGT9tfq8M=";
    finalImageName = "valkey/valkey";
    finalImageTag = "9.1-alpine";
  };
  _unresolved = [
  ];
  _skipped = [
  ];
}
