# Proxmox boot-the-image: boot a disk image built from the services VM's REAL
# image module set, feed it the cloud-init userdata build_proxmox.sh generates,
# and prove the age key lands and sops-nix decrypts with it.
#
# The flake's actual artifact is a VMA — a Proxmox backup container qemu cannot
# boot (its packaging is covered by the `run.sh proxmox` build gate). What CAN
# be booted is a qcow2 built from the same modules: nixos-generators' proxmox
# format is nixpkgs' virtualisation/proxmox-image.nix plus make-disk-image, so
# this suite imports that exact module (grub on /dev/vda, legacy MBR,
# console=ttyS0, virtio initrd modules, cloud-init defaults — the image's own
# bootloader handling, which is part of what boots here; profiles.noBootloader
# would be wrong) and calls make-disk-image with format "qcow2" instead of
# raw-plus-vma-postVM. Everything below the packaging is shared with the
# artifact that gets qmrestore'd.
#
# Substituted, and what each substitution costs:
#   - qcow2, not VMA: the vma-create/zstd packaging step is not exercised.
#     Recovered by the `run.sh proxmox` build gate, which builds the real VMA.
#   - NoCloud seed ISO, not Proxmox cicustom: smaller than it looks — for
#     Linux guests Proxmox's default citype IS nocloud, so the datasource the
#     guest sees is the same; what is lost is qm's assembly of the ISO and the
#     --ipconfig0 static-network metadata (10.0.0.3 cannot mean anything on
#     qemu's slirp network, so the guest falls back to cloud-init's DHCP
#     rendering instead of the static-IP rendering). The userdata itself is
#     generated by the SAME shell as build_proxmox.sh, sed indent pipeline
#     included.
#   - fixture secrets: the production image bakes nixos/secrets.sops.yaml,
#     encrypted to the production recipient, which the committed test key can
#     never decrypt — so the image here bakes the services-vm fixture instead.
#     Coverage lost (that the real file decrypts) is recovered by the
#     key-set-comparison lints, same trade as every other suite.
#
# Real and genuinely under test:
#   - the image module set (configuration.nix + proxmox-image.nix + the
#     flake's image extras), booting from its own grub off the disk
#   - build_proxmox.sh's userdata generation, including the sed indent
#     pipeline on a 3-line age-keygen-style key file — the YAML-indent trap
#     the script's comments document (first line indented, rest at column 0,
#     block scalar terminated, key silently never written)
#   - cloud-init picking up the seed and write_files landing the key at the
#     exact path sops-nix is configured to read, mode 0600
#   - sops-nix decrypting with that key at activation
#   - the qemu guest agent, which is also how Proxmox itself talks to the VM
#
# Deliberately NOT profiles.sopsFixture: that profile also PLANTS the test key
# via an activation script, standing in for cloud-init — but cloud-init is the
# very mechanism under test here, and a pre-planted key would keep every
# assertion below green even with the seed YAML broken. Only the fixture-file
# half of the profile is reproduced (suite-locally, with mkForce like the
# profile). profiles.manualTailscaleAutoconnect is likewise omitted: the unit
# ships in the image and may fail/retry against the unreachable production
# headscale URL — the suite asserts through the guest agent, not through
# multi-user.target, so the retry loop costs nothing and the image stays real.
#
# First-boot finding this suite pins down: sops-nix installs secrets from a
# stage-2 activation script, which runs BEFORE systemd and therefore before any
# cloud-init stage. On the very first boot after imaging, the key does not
# exist yet when activation runs, so /run/secrets stays unpopulated until the
# next activation — the reboot below, or the config-only `nixos-rebuild switch`
# the deploy runbook performs right after imaging. Stack secrets recover
# earlier on the real host (decrypt-sops-envs re-runs minutely and reads the
# key at runtime), but OS-level secrets, TAILSCALE_AUTH_KEY included, wait for
# the second activation. The suite asserts the gap explicitly so a sops-nix
# upgrade that closes it (systemd-based activation ordered after cloud-init)
# shows up as a failing — and then deletable — assertion, not as silence.

{
  pkgs,
  lib,
  sopsModule,
  nixpkgs,
  ...
}:

let
  system = pkgs.stdenv.hostPlatform.system;

  testKeyFile = ../keys/test-age-key.txt;

  imageSystem = import "${nixpkgs}/nixos/lib/eval-config.nix" {
    inherit system;
    modules = [
      sopsModule
      ../../nixos/configuration.nix

      # The image-format module the real VMA build uses (nixos-generators'
      # proxmox format imports exactly this). Brings the bootloader contract:
      # grub on /dev/vda, boot.growPartition, console=ttyS0, virtio initrd
      # modules, cloud-init + qemuGuest defaults, / by-label.
      "${nixpkgs}/nixos/modules/virtualisation/proxmox-image.nix"

      # nixos/flake.nix's inline image-extras module, replicated verbatim.
      # It overlaps proxmox-image.nix on several options with equal values —
      # the same overlap the real image build merges, kept here so a drift
      # between the two (flake edited, module bumped) fails this suite's
      # eval exactly like it would fail the flake's.
      {
        services.cloud-init = {
          enable = true;
          network.enable = true;
        };
        services.qemuGuest.enable = true;
        boot.growPartition = true;
        fileSystems."/" = {
          device = "/dev/disk/by-label/nixos";
          fsType = "ext4";
          autoResize = true;
        };
      }

      # Fixture-file half of profiles.sopsFixture (see header for why the
      # key-planting half must not come along).
      { sops.defaultSopsFile = lib.mkForce ../fixtures/services-vm.sops.yaml; }
    ];
  };

  # The same builder the VMA goes through, minus the VMA packaging: format
  # qcow2 instead of raw + vma-create postVM. partitionTableType comes from
  # the evaluated proxmox module (legacy MBR for the default seabios), so the
  # partition/bootloader layout tracks the real image by construction.
  qcowImage = import "${nixpkgs}/nixos/lib/make-disk-image.nix" {
    inherit pkgs lib;
    config = imageSystem.config;
    inherit (imageSystem.config.proxmox) partitionTableType;
    format = "qcow2";
    diskSize = "auto";
    # Headroom for first-boot writes (docker, journald, cloud-init state).
    # The real disk is grown by Proxmox after restore; nothing grows this one.
    additionalSpace = "2048M";
    # The VMA build ships a nixpkgs channel copy in the image; nothing in the
    # boot contract reads it, and skipping it keeps this multi-minute build
    # smaller. Coverage lost: none — channels are interactive convenience.
    copyChannel = false;
    # make-disk-image runs nixos-install inside a build VM; the services VM's
    # closure needs more than the 1024MB default.
    memSize = 2048;
    name = "services-vm-boot-test-qcow";
  };

  # build_proxmox.sh validates its generated YAML with pyyaml before handing
  # it to the VM; replicate that gate too (it is part of the script's
  # contract, and it fails the build seconds in rather than minutes).
  python = pkgs.python3.withPackages (p: [ p.pyyaml ]);
in

pkgs.runCommand "proxmox-boot"
  {
    nativeBuildInputs = [
      pkgs.qemu_kvm
      pkgs.socat
      pkgs.jq
      pkgs.cdrkit # genisoimage, for the NoCloud seed
      python
    ];
    requiredSystemFeatures = [ "kvm" ];
  }
  ''
    set -euo pipefail

    # -------------------------------------------------------------------------
    # NoCloud seed, generated the way build_proxmox.sh generates its snippet
    # -------------------------------------------------------------------------
    # The sed pipeline and the heredoc below mirror the script line for line.
    # age-keygen output is three lines ("# created:", "# public key:", then
    # the key) — tests/keys/test-age-key.txt has exactly that shape, which is
    # what makes this a real test of the YAML-indent trap: interpolating the
    # file raw would indent only the first line, terminate the block scalar,
    # and cloud-init would reject the userdata.
    AGE_KEY_FILE=${testKeyFile}
    AGE_KEY_INDENTED=$(sed 's/^/      /' "$AGE_KEY_FILE")

    cat > user-data << EOF
    #cloud-config
    write_files:
      - path: /var/lib/sops-nix/sops_age_key.txt
        permissions: '0600'
        owner: root:root
        content: |
    ''${AGE_KEY_INDENTED}

    runcmd:
      - mkdir -p /var/lib/sops-nix
      - chmod 700 /var/lib/sops-nix
    EOF

    # build_proxmox.sh's pyyaml gate, verbatim in spirit: invalid YAML must
    # fail here, not as a silent no-op inside the guest.
    python3 -c 'import sys,yaml; yaml.safe_load(open(sys.argv[1]))' user-data

    # Proxmox generates instance-id and hostname metadata itself; a minimal
    # equivalent is all NoCloud needs to consider the seed valid.
    cat > meta-data << EOF
    instance-id: proxmox-boot-test
    local-hostname: services-vm
    EOF

    # cloud-localds is a thin wrapper over exactly this invocation: the
    # NoCloud datasource looks for a filesystem labelled "cidata".
    genisoimage -quiet -output seed.iso -volid cidata -joliet -rock \
      user-data meta-data

    # -------------------------------------------------------------------------
    # Boot the image
    # -------------------------------------------------------------------------
    # A qcow2 overlay instead of a full copy: same writability guarantee (no
    # -snapshot — writes must survive the in-test reboot) without duplicating
    # a multi-GB image inside the sandbox.
    qemu-img create -q -f qcow2 -b ${qcowImage}/nixos.qcow2 -F qcow2 disk.qcow2

    qemu-system-x86_64 \
      -name proxmox-boot-test \
      -machine accel=kvm -cpu max -smp 2 -m 2048 \
      -drive file=disk.qcow2,if=virtio,format=qcow2,werror=report \
      -cdrom seed.iso \
      -nic user,model=virtio-net-pci \
      -device virtio-serial-pci \
      -chardev socket,id=qga0,path=qga.sock,server=on,wait=off \
      -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 \
      -serial file:serial.log \
      -display none \
      -pidfile qemu.pid \
      -daemonize

    # Everything after this point is bounded twice: every poll loop has its
    # own iteration cap, and this watchdog is the backstop if qemu itself
    # wedges. Its TERM trips the EXIT trap, which dumps the serial log.
    ( sleep 1800; echo "GLOBAL TIMEOUT after 1800s"; kill -TERM $$ ) &
    WATCHDOG=$!

    on_exit() {
      status=$?
      if [ "$status" -ne 0 ]; then
        echo "=== serial.log (last 300 lines) ==="
        tail -n 300 serial.log 2>/dev/null || true
      fi
      kill "$WATCHDOG" 2>/dev/null || true
      [ -f qemu.pid ] && kill "$(cat qemu.pid)" 2>/dev/null || true
    }
    trap on_exit EXIT

    fail() {
      echo "FAIL: $*" >&2
      exit 1
    }

    # -------------------------------------------------------------------------
    # Guest-agent plumbing
    # -------------------------------------------------------------------------
    # One JSON request per connection. The write side is held open (the sleep)
    # until the reply has had time to arrive: qemu's socket chardev treats the
    # client's write-side EOF as a disconnect and DROPS guest-to-host bytes it
    # has not yet relayed, so a plain `printf | socat` loses every reply that
    # is not instantaneous — guest-ping won that race, guest-exec (a fork away)
    # reliably lost it. head exits on the reply line; the outer timeout bounds
    # the whole exchange.
    qga() {
      { printf '%s\n' "$1"; sleep 3; } \
        | timeout 15 socat - UNIX-CONNECT:qga.sock 2>/dev/null \
        | head -n 1 || true
    }

    # Runs a shell command in the guest via guest-exec/guest-exec-status.
    # Returns nonzero if the agent is unreachable or the command never
    # finishes; the command's own exit code and output land in EXEC_CODE /
    # EXEC_OUT / EXEC_ERR either way, so callers can inspect failures.
    guest_exec() {
      local cmd="$1" req resp pid i
      EXEC_CODE="" EXEC_OUT="" EXEC_ERR=""
      # qga spawns /bin/sh with a bare PATH that has no idea about the NixOS
      # system profile — every binary (cloud-init, stat, sha256sum...) is
      # "command not found" without this. Same story on a real Proxmox host
      # driving qm guest exec, incidentally.
      req=$(jq -cn --arg c "export PATH=/run/current-system/sw/bin:\$PATH; $cmd" \
        '{execute:"guest-exec",arguments:{path:"/bin/sh",arg:["-c",$c],"capture-output":true}}')
      resp=$(qga "$req")
      pid=$(printf '%s' "$resp" | jq -r '.return.pid // empty' 2>/dev/null)
      [ -n "$pid" ] || return 1
      for i in $(seq 1 60); do
        resp=$(qga "{\"execute\":\"guest-exec-status\",\"arguments\":{\"pid\":$pid}}")
        if [ "$(printf '%s' "$resp" | jq -r '.return.exited // false' 2>/dev/null)" = "true" ]; then
          EXEC_CODE=$(printf '%s' "$resp" | jq -r '.return.exitcode // 0')
          EXEC_OUT=$(printf '%s' "$resp" | jq -r '.return."out-data" // empty' | base64 -d)
          EXEC_ERR=$(printf '%s' "$resp" | jq -r '.return."err-data" // empty' | base64 -d)
          return 0
        fi
        sleep 1
      done
      return 1
    }

    guest_succeed() {
      guest_exec "$1" || fail "guest agent lost running: $1"
      if [ "$EXEC_CODE" != "0" ]; then
        diag
        fail "guest command failed (exit $EXEC_CODE): $1 | stdout: $EXEC_OUT | stderr: $EXEC_ERR"
      fi
      printf '%s' "$EXEC_OUT"
    }

    # Generous diagnostics before dying: cloud-init's own verdict and logs,
    # the paths under assertion, and everything sops said this boot. The
    # serial tail from the EXIT trap arrives after these. Everything goes to
    # stderr because several guest_succeed call sites run inside command
    # substitutions, where stdout is captured — and then thrown away by the
    # exit that follows.
    diag() {
      {
      echo "=== guest diagnostics ==="
      local c
      for c in \
        "cloud-init status --long" \
        "journalctl -u cloud-init-local -u cloud-init -u cloud-config -u cloud-final --no-pager 2>/dev/null | tail -n 80" \
        "ls -la /var/lib/sops-nix/ /run/secrets/ 2>&1" \
        "journalctl -b --no-pager 2>/dev/null | grep -i sops | tail -n 40" \
        ; do
        echo "--- $c"
        if guest_exec "$c"; then
          printf '%s\n%s\n' "$EXEC_OUT" "$EXEC_ERR"
        else
          echo "(guest-exec unavailable)"
        fi
      done
      } 1>&2
    }

    wait_qga() {
      local i
      for i in $(seq 1 120); do
        if qga '{"execute":"guest-ping"}' | grep -q '"return"'; then
          return 0
        fi
        sleep 2
      done
      fail "$1"
    }

    # -------------------------------------------------------------------------
    # First boot: cloud-init writes the key
    # -------------------------------------------------------------------------
    # qemu-guest-agent is udev-triggered off the virtio port, not gated on
    # multi-user.target — which matters, because tailscale-autoconnect fails
    # and retries against the unreachable production headscale URL in this
    # sandbox, and units that genuinely cannot run here (srv.mount does not
    # exist without hardware-configuration.nix, so decrypt-sops-envs and
    # bootstrap-arcane never start) would stall any target-based wait forever.
    # The same is true on a freshly imaged Proxmox VM, incidentally: the image
    # carries no hardware-configuration.nix either.
    wait_qga "guest agent never answered guest-ping on first boot"

    echo "=> guest agent up (first boot); waiting for cloud-init"

    ci_status=""
    for i in $(seq 1 120); do
      # Poll the artifact, not the binary: result.json is the last thing
      # cloud-init writes, and reading a file cannot be broken by PATH.
      if guest_exec "cat /run/cloud-init/result.json 2>/dev/null && echo CI_DONE"; then
        ci_status="$EXEC_OUT$EXEC_ERR"
        # Loud per-iteration trace: an empty capture here once cost a full
        # debugging cycle (the failure printed nothing to reason about).
        echo "   poll $i: rc=$EXEC_CODE out=$(printf '%s' "$ci_status" | head -c 80)"
        case "$ci_status" in
          # errors list non-empty -> real failure; CI_DONE with empty errors
          # -> finished. The assertions BELOW (key bytes, mode, sops decrypt)
          # remain the actual gate.
          *'"errors": []'*CI_DONE*|*'"errors":[]'*CI_DONE*) break ;;
          *CI_DONE*) diag; fail "cloud-init finished with errors: $ci_status" ;;
        esac
      else
        echo "   poll $i: guest_exec itself failed"
      fi
      sleep 2
    done
    case "$ci_status" in
      *CI_DONE*) echo "=> cloud-init finished: $ci_status" ;;
      *) diag; fail "cloud-init never finished: $ci_status" ;;
    esac

    # (a) The key landed where sops-nix is configured to look, with the mode
    # the userdata asked for, byte-identical to the source file. sha256 rather
    # than piping the content out keeps the comparison exact — including the
    # trailing newline the block scalar must reproduce, the detail the indent
    # pipeline exists to protect.
    owner_mode=$(guest_succeed "stat -c '%a %U:%G' /var/lib/sops-nix/sops_age_key.txt")
    if [ "$owner_mode" != "600 root:root" ]; then
      diag
      fail "age key is $owner_mode, expected '600 root:root'"
    fi

    guest_sha=$(guest_succeed "sha256sum /var/lib/sops-nix/sops_age_key.txt" | cut -d' ' -f1)
    local_sha=$(sha256sum ${testKeyFile} | cut -d' ' -f1)
    if [ "$guest_sha" != "$local_sha" ]; then
      diag
      fail "age key content differs: guest $guest_sha vs source $local_sha — the indent pipeline mangled it"
    fi

    # The runcmd half of the userdata: the key's directory is locked down.
    dir_mode=$(guest_succeed "stat -c '%a' /var/lib/sops-nix")
    if [ "$dir_mode" != "700" ]; then
      diag
      fail "/var/lib/sops-nix is $dir_mode, expected 700 (runcmd chmod did not run)"
    fi

    echo "=> cloud-init wrote the key: mode 0600, content byte-identical"

    # The first-boot gap, asserted on purpose (see header): activation ran
    # before cloud-init could deliver the key, so no OS-level secret exists
    # yet. If this ever fails with the secret PRESENT, sops-nix has started
    # installing secrets after cloud-init — delete this assertion and fold the
    # two boots into one, because the gap it documents is gone.
    guest_succeed "test ! -e /run/secrets/TAILSCALE_AUTH_KEY" > /dev/null
    echo "=> confirmed: no /run/secrets before the second activation (known first-boot gap)"

    # -------------------------------------------------------------------------
    # Second boot: sops-nix decrypts with the delivered key
    # -------------------------------------------------------------------------
    # This is the production sequence too — the runbook follows imaging with a
    # config-only nixos-rebuild switch (a re-activation); a reboot is the same
    # event this suite can trigger without SSH. boot_id distinguishes the new
    # boot from the old one still answering pings on its way down.
    boot1=$(guest_succeed "cat /proc/sys/kernel/random/boot_id")
    qga '{"execute":"guest-shutdown","arguments":{"mode":"reboot"}}' > /dev/null

    echo "=> reboot requested; waiting for the second boot"
    boot2="$boot1"
    for i in $(seq 1 150); do
      sleep 2
      if guest_exec "cat /proc/sys/kernel/random/boot_id"; then
        if [ "$EXEC_CODE" = "0" ] && [ -n "$EXEC_OUT" ] && [ "$EXEC_OUT" != "$boot1" ]; then
          boot2="$EXEC_OUT"
          break
        fi
      fi
    done
    [ "$boot2" != "$boot1" ] || fail "guest never came back from the reboot"

    # (b) Activation runs in stage 2, before systemd — so by the time the
    # agent answers, sops-install-secrets has already run with the key
    # cloud-init persisted. Exact equality with the fixture sentinel: proves
    # decryption AND per-key extraction (the dotenv finding), not merely that
    # some file appeared.
    secret=$(guest_succeed "cat /run/secrets/TAILSCALE_AUTH_KEY")
    if [ "$secret" != "placeholder-replaced-at-runtime" ]; then
      diag
      fail "decrypted secret is '$secret', expected the fixture sentinel"
    fi

    # Same owner/mode contract the vps suite pins for its secrets: sops-nix
    # defaults, root-only.
    secret_stat=$(guest_succeed "stat -c '%a %U:%G' /run/secrets/TAILSCALE_AUTH_KEY")
    if [ "$secret_stat" != "400 root:root" ]; then
      diag
      fail "secret is $secret_stat, expected '400 root:root'"
    fi

    echo "=> sops-nix decrypted with the cloud-init-delivered key on the second activation"

    kill "$WATCHDOG" 2>/dev/null || true
    touch $out
  ''
